### ISSUE TITLE
Refactor code and write tests

### ISSUE THREAD

**Issue by Stepandanci** [ingamorari/ruby-bank-fetch#5]
Please do not close issue.
Open a new pull request from dev branch to master and do not merge it!

## Refactor your code.

1. Read Ruby style guide. Do not use simple letter variables, instead of `b` use `browser`.

2. Unite Fetch logic in one class.

#### Example code structure:

```ruby
class ExampleBank

  def execute
    connect
    fetch_accounts
    fetch_transactions
    save_result
  end

  def connect
    # here you log in to the bank
  end

  def fetch_accounts
    # fetch html data using nokogiri, take only fragment of html.
    html = Nokogiri::HTML.fragment(browser.div(class: "example").html)
    parse_accounts(html)
  end

  def fetch_transactions
    # go to transactions, save html
    parse_transactions(account, html)
  end

  def parse_accounts(html)
    # parse accounts here
  end

  def parse_transactions(account, html)
    # parse transactions here
  end
end
```

3. Update keys and data structure

Read again your test task, and check example.
```json
{
  "accounts": [
    {
      "name": "account1",
      "currency": "MDL",
      "balance": 300.22,
      "nature": "account",
      "transactions": [
        {
            "date": "2015-01-15",
            "description": "bought food",
            "amount": -20.31,
            "currency": "MDL",
            "account_name": "account1"
        }
      ]
    }
  ]
}
```
date must be it json format example: "2020-08-20",
balance and amount must be float not string.

## Write tests

You should write a test that checks the data from demo bank.

1. Read about Rspec. It is a framework for test your code.

- https://rspec.info
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

2. Create `example_spec.rb` file.

3. Write specs for `parse_accounts` and `parse_transactions`.

4. Take HTML from bank and save it in a file (check screenshot).
`html_example = Nokogiri::HTML(File.read('accounts.html'))`

`https://demo.bank-on-line.ru/?registered=demo#Contracts`
![image](https://user-images.githubusercontent.com/29861352/90755159-87adf680-e2e3-11ea-8e64-0203aa9883e7.png)

5. Call method for parse accounts and send HTML data. `parse_accounts(html_example)`

6. Check the number of accounts and show an example account in a hash format.

Example:
```ruby
it 'check number of accounts and show an example account' do
  html_example = Nokogiri::HTML(File.read('accounts.html'))
  accounts = parse_accounts(html_example) # NOTE: It is my example, not a real code.

  expect(accounts.count).to eq(5)
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "40817840400000055321",
      "currency"     => "USD",
      "balance"      => 100000.00,
      "nature"       => "account",
      "transactions" => []
    }
  )
end
```

7. Do the same for transactions.

Good luck!

**Comment by Stepandanci** [comment]
If you have any questions, write in this issue.

**Comment by ingamorari** [comment]
I finished the task and put the changes on the nokogiri branch.

**Comment by Stepandanci** [comment]
Create pull request from your later branch `nokogiri` to `master`.  
And close previous pull request.

**Comment by ingamorari** [comment]
I closed the previous pull request and created new pull request from latest branch nokogiri to master.

**Comment by Stepandanci** [comment]
Your test task looks better.

Resolve my last comments and do not close your last pull request.

**Comment by ingamorari** [comment]
I resolved the last comments

**Comment by Stepandanci** [comment]
**Congratulations!**
You have completed the test task

You will be invited for a second interview.
